### ISSUE TITLE
Error while linking

### ISSUE THREAD

**Issue by croisez** [Sermus/ESP8266_Adafruit_ILI9341#1]
The eagle.app.v6.cpp.ld file was not present in my sdk esp_iot_sdk_v0.9.5 version, so I replaced it with eagle.app.v6.ld.
After that, I got an error during linking.

Could you help me resolve this issue?

<pre><code>
esp8266@esp8266-VirtualBox:~/esp8266/ESP8266_Adafruit_ILI9341$ make
C+ driver/Adafruit_GFX_AS.cpp
C+ driver/Adafruit_ILI9341_fast_as.cpp
CC driver/Font16.c
CC driver/Font32.c
CC driver/Font64.c
CC driver/Font7s.c
CC driver/hspi.c
CC driver/mini-printf.c
CC driver/uart.c
CC math/cordic.c
C+ user/cube.cpp
C+ user/routines.cpp
C+ user/ui.cpp
C+ user/user_main.cpp
AR build/app_app.a
LD build/app.out
build/app_app.a(routines.o): In function `operator delete[](void*)':
routines.cpp:(.text+0x4c): undefined reference to `__init_array_start'
routines.cpp:(.text+0x50): undefined reference to `__init_array_end'
collect2: error: ld returned 1 exit status
make: *** [build/app.out] Error 1
</code></pre>

**Comment by Sermus** [comment]
Hello, this is what in the linker script (eagle.app.v6.cpp.ld):

/\* This linker script generated from xt-genldscripts.tpp for LSP . _/
/_ Linker Script for ld -N */
MEMORY
{
  dport0_0_seg :                        org = 0x3FF00000, len = 0x10
  dram0_0_seg :                         org = 0x3FFE8000, len = 0x14000
  iram1_0_seg :                         org = 0x40100000, len = 0x8000
  irom0_0_seg :                         org = 0x40240000, len = 0x32000
}

PHDRS
{
  dport0_0_phdr PT_LOAD;
  dram0_0_phdr PT_LOAD;
  dram0_0_bss_phdr PT_LOAD;
  iram1_0_phdr PT_LOAD;
  irom0_0_phdr PT_LOAD;
}

/\*  Default entry point:  _/
ENTRY(call_user_start)
PROVIDE(_memmap_vecbase_reset = 0x40000000);
/_ Various memory-map dependent cache attribute settings: */
_memmap_cacheattr_wb_base = 0x00000110;
_memmap_cacheattr_wt_base = 0x00000110;
_memmap_cacheattr_bp_base = 0x00000220;
_memmap_cacheattr_unused_mask = 0xFFFFF00F;
_memmap_cacheattr_wb_trapnull = 0x2222211F;
_memmap_cacheattr_wba_trapnull = 0x2222211F;
_memmap_cacheattr_wbna_trapnull = 0x2222211F;
_memmap_cacheattr_wt_trapnull = 0x2222211F;
_memmap_cacheattr_bp_trapnull = 0x2222222F;
_memmap_cacheattr_wb_strict = 0xFFFFF11F;
_memmap_cacheattr_wt_strict = 0xFFFFF11F;
_memmap_cacheattr_bp_strict = 0xFFFFF22F;
_memmap_cacheattr_wb_allvalid = 0x22222112;
_memmap_cacheattr_wt_allvalid = 0x22222112;
_memmap_cacheattr_bp_allvalid = 0x22222222;
PROVIDE(_memmap_cacheattr_reset = _memmap_cacheattr_wb_trapnull);

SECTIONS
{

  .dport0.rodata : ALIGN(4)
  {
    _dport0_rodata_start = ABSOLUTE(.);
    *(.dport0.rodata)
    *(.dport.rodata)
    _dport0_rodata_end = ABSOLUTE(.);
  } >dport0_0_seg :dport0_0_phdr

  .dport0.literal : ALIGN(4)
  {
    _dport0_literal_start = ABSOLUTE(.);
    *(.dport0.literal)
    *(.dport.literal)
    _dport0_literal_end = ABSOLUTE(.);
  } >dport0_0_seg :dport0_0_phdr

  .dport0.data : ALIGN(4)
  {
    _dport0_data_start = ABSOLUTE(.);
    *(.dport0.data)
    *(.dport.data)
    _dport0_data_end = ABSOLUTE(.);
  } >dport0_0_seg :dport0_0_phdr

  .data : ALIGN(4)
  {
    _data_start = ABSOLUTE(.);
    _(.data)
    *(.data._)
    _(.gnu.linkonce.d._)
    _(.data1)
    *(.sdata)
    *(.sdata._)
    _(.gnu.linkonce.s._)
    _(.sdata2)
    *(.sdata2._)
    _(.gnu.linkonce.s2._)
    *(.jcr)
    _data_end = ABSOLUTE(.);
  } >dram0_0_seg :dram0_0_phdr

  .rodata : ALIGN(4)
  {
    _rodata_start = ABSOLUTE(.);
    _(.rodata)
    *(.rodata._)
    _(.gnu.linkonce.r._)
    *(.rodata1)
    __XT_EXCEPTION_TABLE__ = ABSOLUTE(.);
    _(.xt_except_table)
    *(.gcc_except_table)
    *(.gnu.linkonce.e._)
    _(.gnu.version_r)
    *(.eh_frame)
    . = (. + 3) & ~ 3;
    /_  C++ constructor and destructor tables, properly ordered:  _/
    __init_array_start = ABSOLUTE(.);
    KEEP (_crtbegin.o(.ctors))
    KEEP (_(EXCLUDE_FILE (_crtend.o) .ctors))
    KEEP (_(SORT(.ctors._)))
    KEEP (_(.ctors))
    __init_array_end = ABSOLUTE(.);
    KEEP (_crtbegin.o(.dtors))
    KEEP (_(EXCLUDE_FILE (_crtend.o) .dtors))
    KEEP (_(SORT(.dtors._)))
    KEEP (_(.dtors))
    /_  C++ exception handlers table:  _/
    **XT_EXCEPTION_DESCS** = ABSOLUTE(.);
    *(.xt_except_desc)
    *(.gnu.linkonce.h._)
    **XT_EXCEPTION_DESCS_END** = ABSOLUTE(.);
    _(.xt_except_desc_end)
    *(.dynamic)
    *(.gnu.version_d)
    . = ALIGN(4);       /_ this table MUST be 4-byte aligned */
    _bss_table_start = ABSOLUTE(.);
    LONG(_bss_start)
    LONG(_bss_end)
    _bss_table_end = ABSOLUTE(.);
    _rodata_end = ABSOLUTE(.);
  } >dram0_0_seg :dram0_0_phdr

  .bss ALIGN(8) (NOLOAD) : ALIGN(4)
  {
    . = ALIGN (8);
    _bss_start = ABSOLUTE(.);
    _(.dynsbss)
    *(.sbss)
    *(.sbss._)
    _(.gnu.linkonce.sb._)
    _(.scommon)
    *(.sbss2)
    *(.sbss2._)
    _(.gnu.linkonce.sb2._)
    _(.dynbss)
    *(.bss)
    *(.bss._)
    _(.gnu.linkonce.b._)
    _(COMMON)
    . = ALIGN (8);
    _bss_end = ABSOLUTE(.);
    _heap_start = ABSOLUTE(.);
/_    _stack_sentry = ALIGN(0x8); _/
  } >dram0_0_seg :dram0_0_bss_phdr
/_ __stack = 0x3ffc8000; */

  .text : ALIGN(4)
  {
    _stext = .;
    _text_start = ABSOLUTE(.);
    _(.entry.text)
    *(.init.literal)
    *(.init)
    *(.literal .text .literal._ .text.\* .stub .gnu.warning .gnu.linkonce.literal.\* .gnu.linkonce.t._.literal .gnu.linkonce.t._)
    *(.fini.literal)
    *(.fini)
    *(.gnu.version)
    _text_end = ABSOLUTE(.);
    _etext = .;
  } >iram1_0_seg :iram1_0_phdr

  .lit4 : ALIGN(4)
  {
    _lit4_start = ABSOLUTE(.);
    _(_.lit4)
    _(.lit4._)
    _(.gnu.linkonce.lit4._)
    _lit4_end = ABSOLUTE(.);
  } >iram1_0_seg :iram1_0_phdr

  .irom0.text : ALIGN(4)
  {
    _irom0_text_start = ABSOLUTE(.);
    *(.irom0.literal .irom.literal .irom.text.literal .irom0.text .irom.text)
    _irom0_text_end = ABSOLUTE(.);
  } >irom0_0_seg :irom0_0_phdr
}

/\* get ROM code address */
INCLUDE "../ld/eagle.rom.addr.v6.ld"

**Comment by croisez** [comment]
Used your file, but missed something:

<pre><code>
/home/esp8266/esp8266/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld:/home/esp8266/esp8266/esp_iot_sdk_v0.9.5/ld/eagle.app.v6.cpp.ld:71: syntax error
collect2: error: ld returned 1 exit status
make: *** [build/app.out] Error 1
</code></pre>

This is an autogenerated file. Did you generate it yourself?

**Comment by Sermus** [comment]
I used the one coming with the unofficial devkit
https://github.com/CHERTS/esp8266-devkit

**Comment by croisez** [comment]
Yesss! Now it works.
Thank you for your help, and for discovering this unofficial devkit.
What framerate do you achieve on the ILI9341? My goal is to build VR screens for both eyes, transmitting pictures by WiFi,  so I hope to get a decent framerate

**Comment by Sermus** [comment]
I don't believe it's possible with ESP8266 and ILI9341. The reasons are:
1) The pixel framerate wouldn't be so high. Even at 40MHz theoretical upper
limit is about 32FPS. Theoretical means you'll push in pixels without any
delays. But there are delays. There are SPI delays, there will be memory
access delays and etc. If i remember correct maximum i could get filling
screen with one color was something about 20FPS, but in your application
even this is not achievable. See point 2.
2) To store a complete framebuffer you need 150KB of RAM. ESP8266 doesn't
have so much. This means you'll have to transmit your data in parts which
will introduce additional latency. And i didn't say a bit about wifi
transfer issues which you'll definitely have (i didn't check myself, but
forum posts hint this is the most buggy part of ESP8266's SDK and FW).

2015-03-17 12:02 GMT+03:00 croisez notifications@github.com:

**Comment by croisez** [comment]
ok.
By the way, what is you esp kind of board?
I am using ESP-03, with 14 pins.
And you?
The ILI does not react to the ESP firmware, and I don't know what is the
reason for this?

_L_OUIS

2015-03-17 10:14 GMT+01:00 Sermus notifications@github.com:

**Comment by Sermus** [comment]
I use esp09 but this shouldn't matter.
How do you handle GPIO15? To let ESP start properly it shall be pulled down. Most instructions [wrongly] recomend just put GPIO on the ground. In such case you, of course, won't get TFT working because GPIO is used as CS in my code. The best you can do is to put a resistor [i used 10kOhm] between GPIO15 and ground.

**Comment by croisez** [comment]
I just received my new logic analyser. I first tested it with an Arduino
controlling ILI9341 display, and i can analyse SPI signals.
But with my ESP8266-03 board, with your code running, no SPI signal is
output from the PINs.
I wonder if the SPI configuration on the ESP must not be changed, due to
the board rev. is different (03 vs 09).
Also, do you use hardware SPI or bitbanging?
Perhaps SDK version is important. I am using 0.9.5 (latest)

_L_OUIS

2015-03-19 5:37 GMT+01:00 Sermus notifications@github.com:

**Comment by Sermus** [comment]
What is the sampling rate you used. And to what pins you attached?
Could you please check GPIO15 is not shortcircuited to the ground (there shall be a pulling resistor)

I also built it up with SDK 0.9.5

**Comment by Sermus** [comment]
And yes, it's hardware implementation. With bitbanging i'd never get such speed.

**Comment by croisez** [comment]
I used same pin defined in your code: clk = gpio14, miso = gpio12, cs =
gpio15, dc = gpio2.
Here is pin-out for rev-03 board.
[image: Images intégrées 1]
Also, gpio15 is pulled-down with a 1k resistor

I can see the debug traces in the serial terminal upon power-up of the
board.
But no signal on SPI pins.
Honestly, i don't know how to debug it.

_L_OUIS

2015-04-03 10:46 GMT+02:00 Andrey Filimonov notifications@github.com:

**Comment by Sermus** [comment]
So, did i get you correctly. You don't see any level change on any of the SPI lines, correct?
If you write a simple program trying to put GPIO2 to high and low states do you see it in logic analyzer?

**Comment by croisez** [comment]
it is correct.
I will write this program. I Keep you in touch.

_L_OUIS

2015-04-03 12:28 GMT+02:00 Andrey Filimonov notifications@github.com:
