### ISSUE TITLE
screen orientation problem. 

### ISSUE THREAD

**Issue by alonewolfx2** [Sermus/ESP8266_Adafruit_ILI9341#2]
firstly thank you for your work.and i have  a problem. cube working fine. it seems drawstring have a problem. everything flipped its not working correctly. can you help me ?

**Comment by Sermus** [comment]
Hello, I suspended these activities due to family problems. Anyway, can you
send a photo of how this wrong output look like?

Andrey.
Sent from my mobile device.
06 мая 2015 г. 19:15 пользователь "alonewolfx2" notifications@github.com
написал:

**Comment by alonewolfx2** [comment]
ofcourse. 
![img_6832](https://cloud.githubusercontent.com/assets/9630594/7499187/9e95b8b4-f42e-11e4-8200-ab224d444adc.jpg)

**Comment by alonewolfx2** [comment]
0.0 point should be left side on the picture and it seems all numbers reversed

**Comment by Sermus** [comment]
This seems to depend on screen module configuration.
Someone before reported that colours are messed like screen controller
swaps bytes in colours. You report inverted coordinate system. All my
modules seem to work correct with color and and coordinate spaces.

Anyway, can you send me a photo of how my ui demo looks like for you.
Andrey.
Sent from my mobile device.
06 мая 2015 г. 20:31 пользователь "alonewolfx2" notifications@github.com
написал:

**Comment by alonewolfx2** [comment]
ui demo ?

**Comment by Sermus** [comment]
Please refer to sample code section of read me file. Find code word
UIDEMO )))

Andrey.
Sent from my mobile device.
06 мая 2015 г. 20:42 пользователь "alonewolfx2" notifications@github.com
написал:

**Comment by Sermus** [comment]
Did you manage to run the code in UIDEMO mode?

Can you try to invoke setRotation explicitly and see what happens then?

**Comment by alonewolfx2** [comment]
i am using your old code from espressif dev kit. i tried last commit but i didnt make it work. its not working on my device. and i found my screen driver is ili9340(chinese seller said ili9341.) actually its not very different chip. its working adafruit ili9341 library just 2 line change. i saw new commit and hspi.c is different. and new code not working. 

```
data[0] = 0x48;     //C8       //48 68ç»”æ §ç�†//28 E8 å¦¯î�„ç�†
    //transmitCmdData(0x36, data, 1);       // Memory Access Control for ili9341
    transmitCmdData(0x40, data, 1);          //Memory Access Control for ili9340
    transmitCmdData(0x08, data, 1);          //Memory Access Control for ili9340
```

**Comment by alonewolfx2** [comment]
how can i work with new code? any suggestion

**Comment by Sermus** [comment]
Espressif dev kit doesn't have my code for ILI9341. This is another guy's code.

So you're saying that the code from UDK you can make it work with these two lines change, but you can't make my code work with the same change. Did i get it correct?

**Comment by alonewolfx2** [comment]
yes you are right.same change not work with your code.

**Comment by Sermus** [comment]
Hm, it's hard to say why just looking into code. What i'd do in this
situation is connecting logic analyzer and capturing the actual SPI
exchange.
I did a lot of such debugging writing that lib.

2015-05-08 14:00 GMT+03:00 alonewolfx2 notifications@github.com:

**Comment by alonewolfx2** [comment]
firstly you defined cs pin to gpio15 but perfer used gpio4 can i change this? i am using esp-03 and gpio15 connected to gnd with 2k pulldown resistor. https://github.com/Perfer/esp8266_ili9341/blob/master/include/ili9341.h#L43
https://github.com/Sermus/ESP8266_Adafruit_ILI9341/blob/master/driver/hspi.c#L26

**Comment by Sermus** [comment]
Nop, it uses hardware CS line control which is possible only for GPIO15. 
If it's connected through 2k resistor (i mean not shortcircuited to gnd) you still should be able to use it as CS.

**Comment by alonewolfx2** [comment]
i used 2k2 resistor soo problem isnt it. hmm. any idea ?

**Comment by Sermus** [comment]
Do you have 15k?

**Comment by alonewolfx2** [comment]
i have 10k. i can connect together. 12k is enough?

**Comment by Sermus** [comment]
yes, it shall be absolutely enough

**Comment by alonewolfx2** [comment]
12k resistor seems to solved all problem :) Thank you. its working now. screen orientation is right.
also i will push pull request for ili9340 init. or maybe you can?
