### ISSUE TITLE
Pin connections

### ISSUE THREAD

**Issue by rith87** [Sermus/ESP8266_Adafruit_ILI9341#3]
In the quick wiring guide, I saw:

MISO --> GPIO12

My understanding is that the ESP8266 is the master and is pushing bits to the slave LCD screen. Shouldn't it be MOSI --> GPIO12 instead?

**Comment by Sermus** [comment]
Yes, you're absolutely right, this is a typo of course.

2015-06-10 11:49 GMT+03:00 rith87 notifications@github.com:

**Comment by rith87** [comment]
Cool. Just checking. Thanks for the quick response!

**Comment by Sermus** [comment]
Corrected
