### ISSUE TITLE
How spi speed @80mhz? 

### ISSUE THREAD

**Issue by tontito** [Sermus/ESP8266_Adafruit_ILI9341#5]
Hi Sermus,
How do I do that spi speed @40mhz to @80mhz overclock ?

**Comment by Sermus** [comment]
Hi Volki,
I was never able to make ILI9341 work at 80MHz. 40 was my top.
If you can please let me know.

Sermus.

2015-07-01 1:15 GMT+03:00 Volki notifications@github.com:

**Comment by rexnanet** [comment]
Hi,
I've stumble upon this as I was trying to get the display to work for the first time. The speed was set to 80Mhz hardcoded on the ILI9341 driver but all I was getting was a blank screen.
Finally found it and tested with 40MHz and it worked! So I'm investigating if it's really possible to run it at 80MHz...
I've been able to run it at 64MHz but on a SMT32. I don't think that it is possible to setup speeds between 40 and 80MHz on the ESP8266.
It might be that the wires are a bit big for these speeds. I'm going to try again with shorter cables when I have the chance...

Rex.
