### ISSUE TITLE
How to use the fonts in the program ESP8266_Adafruit_ILI9341

### ISSUE THREAD

**Issue by sfranchin63** [Sermus/ESP8266_Adafruit_ILI9341#8]
Hi Sermus,
I tried to change the size of the text by changing for example HEADERTEXT 2 to 7
LINETEXT 2 to 7 but the text disappears.
How can I write the largest text and how can I use the various fonts: Font16, Font32, etc.
You can also give me an example of using the mini_vsnprintf function.
Thank you.
Best regards
Stefano

**Comment by Sermus** [comment]
This is an ancient code and i don't remember exactly, but not all of these fonts contain all the characters. For example font7 has only digits so if you try to render something else it will be rendered as empty space. This is explicitly claimed in font7s.c header.
