### ISSUE TITLE
drawCentreString infinite loop causes crash

### ISSUE THREAD

**Issue by ginamdar** [Sermus/ESP8266_Adafruit_ILI9341#9]
Hi,

I am trying to use your functions by copying inside adafruit library and seems working fine for initial test. Except one minor issue in drawCentrString function
```   
#ifdef LOAD_FONT7
		if (size==7) len += *(widtbl_f7s+ascii-32)+2;
		*pointer++; // This should be out of the #ifdef block
#endif
	}
```

Fyi

I copied below functions and pasted inside Adafruit_GFX.h and their implementation in cpp file
```
    int drawChar(char c, uint16_t x, uint16_t y, uint8_t size);
    int drawString(const char *string, uint16_t poX, uint16_t poY, uint8_t size);
    int drawCentreString(const char *string, uint16_t dX, uint16_t poY, uint8_t size);
    int drawRightString(const char *string, uint16_t dX, uint16_t poY, uint8_t size);
    int drawFloat(float floatNumber,uint8_t decimal,uint16_t poX, uint16_t poY, uint8_t size);
    int drawUnicode(uint16_t uniCode, uint16_t x, uint16_t y, uint8_t size);
    int drawNumber(long long_num,uint16_t poX, uint16_t poY, uint8_t size);
```

also declared macro in same header file on top, and then copied Font16.h/Font16.c in same Adafruit_GFX_Library/ folder inside arduino Libraries/
``` 
#define LOAD_FONT2
#include "Font16.h"
```

And then basically used the drawWireFrame and drawPlaceHolder inside my .ino project 

Currently im testing it with Huzzah ESP8266 and [TFT](https://www.aliexpress.com/item/1pcs-J34-F85-240x320-2-8-SPI-TFT-LCD-Touch-Panel-Serial-Port-Module-with-PCB/32801794132.html?spm=a2g0s.9042311.0.0.MVFoZD) display. Also to note i need to re-flow the J1 joint on back of display to work effectively with 3.3v. 

Thank you for these awesome functions.

**Comment by Sermus** [comment]
You're right, thank you. Fixed.
